# Generated by Django 4.1.4 on 2023-01-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0004_userprofile_alter_personal_expense_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expenditure',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='income',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
