# Generated by Django 4.1.4 on 2023-01-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0005_userprofile_expenditure_userprofile_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='expenditure',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='income',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
