# Generated by Django 4.1.4 on 2023-01-01 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('splitter', '0006_alter_userprofile_expenditure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_income',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
