# Generated by Django 4.1.4 on 2023-01-01 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0007_alter_personal_income_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='expenditure',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='income',
        ),
    ]
