# Generated by Django 4.1.4 on 2023-01-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0011_alter_simple_transaction_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('entertainment', 'Entertainment'), ('travelling', 'Travelling'), ('groceries', 'Groceries')], default='food', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='splitroom',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('entertainment', 'Entertainment'), ('travelling', 'Travelling'), ('groceries', 'Groceries')], default='food', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personal_expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('entertainment', 'Entertainment'), ('travelling', 'Travelling'), ('groceries', 'Groceries')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personal_income',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('entertainment', 'Entertainment'), ('travelling', 'Travelling'), ('groceries', 'Groceries')], max_length=20),
        ),
        migrations.AlterField(
            model_name='simple_transaction',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('entertainment', 'Entertainment'), ('travelling', 'Travelling'), ('groceries', 'Groceries')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
