# Generated by Django 4.1.4 on 2023-01-04 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0013_userprofile_expense_userprofile_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_debts', to='splitter.splitroom'),
        ),
    ]
