# Generated by Django 4.1.4 on 2023-01-04 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('splitter', '0015_debt_created_at_delete_simple_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
